apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: kubernetes-dev
build:
  artifacts:
  - image: registry.digitalocean.com/dataplane-dev/dataplane-main-dev
    docker:
      dockerfile: ./kubernetes-dev/Dockerfile.main
deploy:
  kubectl:
    manifests:
    - ./kubernetes-dev/do-dp-main-deployment.yaml
