apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: kubernetes-dev
build:
  artifacts:
  - image: dataplane/dataplane-main-dev
    docker:
      dockerfile: ./kubernetes-dev/Dockerfile.main
deploy:
  kubectl:
    manifests:
    - ./kubernetes-dev/dp-main-deployment.yaml
